# English: See the configuration tutorial at http://dev.bukkit.org/bukkit-plugins/openguild/pages/config-configuration/
# polski: Patrz poradnik konfiguracji na https://github.com/grzegorz2047/OpenGuild2047/wiki/Konfiguracja
# svenska: Det finns inte konfiguration guide på svenska :(
language: PL
teampvp: false
teampvp-msg: false
home-command: true
teleport-cooldown: 10
spawn:
  location-max: [world, 50, 50]
  location-min: [world, -50, -50]
  block-guild-creating: true
  message: '&cYou are not allowed to do this at the servers spawn point!'
cuboid:
  min-radius: 15
  max-radius: 50
  canenterarea: true
  extra-protection: true
  breaking-blocks:
    item-types: [DIAMOND_PICKAXE]
    damage: 0
hardcore-bans:
  enabled: true
  ban-time: 1h
  kick-message: '&4You are dead! &7The revival will occur &6%TIME&7!'
  login-message: '&7You are banned for death to &6%TIME'
database: FILE
file-dir: plugins/OpenGuild2047/guilds.yml
snooper: true
mysql:
  address: localhost
  database: openguild
  login: user
  password: password
  debug: false
playerprefixtag: true
tag-color: '&6'
guildprefixinchat: true
forbiddenguildnames:
required-items:
- 'WOOD:2'
