name: OpenGuild2047
description: OpenGuild2047 to publiczny plugin na gildie dla wszystkich tworzony przez Grzegorza2047
authors: [grzegorz2047]
website: http://www.youtube.com/grzegorz20471
version: 0.2
#softdepend: [NametagEdit]
main: pl.grzegorz2047.openguild2047.OpenGuild
commands:
  guild:
    description: Commands about guilds
    aliases: [g, gildia]
